apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-db
  template:
    metadata:
      labels:
        app: user-service-db
    spec:
      containers:
        - name: postgres
          image: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: user-service-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: user-service-data
          persistentVolumeClaim:
            claimName: user-service-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-db
spec:
  selector:
    app: user-service-db
  ports:
    - port: 5434
      targetPort: 5432
  type: ClusterIP