configurl: http://config-server:8090
spring:
  application:
    name: notification-service
  cloud:
    config:
      profile: local
      fail-fast: true
      retry:
        initial-interval: 1500
        multiplier: 1.5
        max-attempts: 10
        max-interval: 10000
  config:
    import: configserver:${configurl}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-1:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest

kafka:
  topics:
    passwordResetEventsTopic: password-reset-events
    userActivationEventsTopic: user-activation-events

server:
  port: 9080

logging:
  level:
    com.gygy.notificationservice: INFO
    org.springframework.kafka: INFO
