spring:
  application:
    name: notification-service

  cloud:
    config:
      enabled: false  # config-server kullanmıyoruz, bu yüzden kapalı

  mail:
    host: smtp.gmail.com
    port: 587
    username: gulcanbal098@gmail.com            # Gmail adresin
    password: jule xtir jlso ziru                 # Gmail'den aldığın uygulama şifresi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest

kafka:
  topics:
    passwordResetEventsTopic: password-reset-events
    userActivationEventsTopic: user-activation-events
    contractDetailCreatedTopic: contract_detail_created_topic
    billCreatedEventsTopic: bill-created-events
    billOverdueEventsTopic: bill-overdue-events
    billPaidEventsTopic: bill-paid-events
    paymentFailedEventsTopic: payment-failed-events
    paymentSuccessEventsTopic: payment-success-events
    userRoleChangedTopic: user-role-changed-topic
    userPermissionChangedTopic: user-permission-changed-topic
    individualCustomerCreatedTopic: individual-customer-created-topic
    individualCustomerUpdatedTopic: individual-customer-updated-topic
    corporateCustomerCreatedTopic: corporate-customer-created-topic
    corporateCustomerUpdatedTopic: corporate-customer-updated-topic
    planCampaignTopic: plan-campaign-topic
    notificationPreferencesChangedTopic: notification-preferences-changed-topic

server:
  port: 9080

logging:
  level:
    com.gygy.notificationservice: INFO
    org.springframework.kafka: INFO
