spring:
  application:
    name: contract-service
  datasource:
    url: "jdbc:postgresql://localhost:5436/contract-service"
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
server:
  port: 9030

