global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"


scrape_configs:
  - job_name: "all-services"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['config-server-app:8090', 'discovery-server:8888', 'user-service:9010', 'customer-service:9020', 'contract-service:9030', 'plan-service:9040', 'payment-service:9050', 'customer-support-service:9060', 'analytics-service:9070', 'notification-service:9080']

  - job_name: "config-server-app"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['host.docker.internal:8090', 'config-server-app:8090']

  - job_name: "discovery-server-app"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["discovery-server:8888"]

  - job_name: "user-service-app"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:9010"]

  - job_name: "customer-service-app"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:9020", "customer-service:9020"]

  - job_name: "contract-service-app"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["contract-service:9030"]

  - job_name: "plan-service-app"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["plan-service:9040"]

  - job_name: "payment-service-app"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:9050"]

  - job_name: "customer-support-service-app"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["customer-support-service:9060"]

  - job_name: "analytics-service-app"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["analytics-service:9070"]

  - job_name: "notification-service-app"
    scrape_interval: 2s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["notification-service:9080"]

  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "zipkin"
    scrape_interval: 5s
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["zipkin:9411"]

#  - job_name: "self"
#    scrape_interval: 30s
#    static_configs:
#      - targets: ["localhost:9090"]
