configurl: http://localhost:8090

spring:
  application:
    name: customer-service
  cloud:
    config:
      profile: local
  config:
    import: configserver:${configurl}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 9020