configurl: http://localhost:8090

spring:
  application:
    name: customer-service
  cloud:
    config:
      profile: local
  config:
    import: configserver:${configurl}

  kafka:
    consumer:
      group-id: customer-read-group, notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: notificationPreferencesChangedEvent:com.gygy.customerservice.infrastructure.messaging.event.NotificationPreferencesChangedEvent,createdIndividualCustomerReadEvent:com.gygy.customerservice.infrastructure.messaging.event.db.CreatedIndividualCustomerReadEvent
        spring.json.value.default.type: com.gygy.customerservice.infrastructure.messaging.event.db.CreatedIndividualCustomerReadEvent

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    com.gygy.customerservice: DEBUG
    com.gygy.customerservice.infrastructure.outbox: DEBUG

encryption:
  secret-key: "GygyTelecomCRM2024!@#$%^&*()"
  salt-key: "4202MRCmoceleTygyG!@#$%^&*()"

server:
  port: 9020
