apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: umutgu/config-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_CLOUD_CONFIG_PROFILE
          value: "dev"
        - name: CONFIGURL
          value: "http://config-server:8090"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  ports:
  - port: 8090
    targetPort: 8090
  type: ClusterIP