apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
      - name: discovery-server
        image: 884574953537.dkr.ecr.eu-central-1.amazonaws.com/gygy/discovery-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        env:
        - name: SPRING_CLOUD_CONFIG_PROFILE
          value: "dev"
        - name: CONFIGURL
          value: "http://config-server:8090"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    app: discovery-server
  ports:
  - port: 8888
    targetPort: 8888
  type: ClusterIP