spring:
  application:
    name: plan-service

  datasource:
    url: jdbc:postgresql://localhost:5445/planService
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  banner:
    location: classpath:banner.txt    # Use custom banner file
    charset: UTF-8                    # Banner file encoding
    # If you want to disable banner completely:
    # banner-mode: "off"é

server:
  port: 9040

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
