configurl: http://localhost:8090
spring:
  application:
    name: customer-support-service
  cloud:
    config:
      profile: local
  config:
    import: configserver:${configurl}
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 9060

app-config:
  kafka:
    topics:
      ticket-created: ticket-created-events
      ticket-response: ticket-response-events
      ticket-status-change: ticket-status-change-events