spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:postgresql://localhost:5432/user-service"
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: user-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 9010

jwt:
  expiration: 7200000
  secret: "KRbQDv3hU8U9BOF0kjynHH35tpPiOoiBEJVooJ9Z1yTZZXaqlha0xHXx1DOlVvU"

logging:
  level:
    com.gygy.userservice.core.pipeline: DEBUG
    com.gygy: INFO
    root: WARN
# Error
# Warning
# Info
# Debug
# Trace