configurl: http://localhost:8090
spring:
  application:
    name: analytics-service
  cloud:
    config:
      profile: local
  config:
    import: configserver:${configurl}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: analytics-service-group
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.trusted.packages: com.gygy.common.events.*
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/analytics-service?authSource=admin

kafka:
  topics:
    ticket-created: ticket-created-events
    ticket-response: ticket-response-events
    ticket-status-change: ticket-status-change-events

server:
  port: 9070

