server:
  port: 9021

spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

debezium:
  connector:
    name: outbox-connector
    database:
      hostname: localhost
      port: 5437
      user: postgres
      password: test
      dbname: customer-service
      server-name: customer-service
      schema-include-list: public
      table-include-list: public.outbox
    offset:
      storage: org.apache.kafka.connect.storage.FileOffsetBackingStore
      file: offset.dat
      flush-interval-ms: 60000
    plugin:
      name: pgoutput
    slot:
      name: outbox_slot
    publication:
      name: outbox_publication
      autocreate-mode: filtered
    format:
      key: json
      value: json
    transforms:
      unwrap:
        type: io.debezium.transforms.ExtractNewRecordState
        drop-tombstones: false
        delete-handling-mode: rewrite
        add-fields: op,source.ts_ms
        add-headers: op

logging:
  level:
    com.gygy.debezium: DEBUG
    io.debezium: INFO 