apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-support-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-support-service
  template:
    metadata:
      labels:
        app: customer-support-service
    spec:
      containers:
      - name: customer-support-service
        image: 884574953537.dkr.ecr.eu-central-1.amazonaws.com/gygy/customer-support-service
        imagePullPolicy: Always
        ports:
        - containerPort: 9060
        env:
        - name: SPRING_CLOUD_CONFIG_PROFILE
          value: "dev"
        - name: CONFIGURL
          value: "http://config-server:8090"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9060
          initialDelaySeconds: 90
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9060
          initialDelaySeconds: 90
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: customer-support-service
spec:
  selector:
    app: customer-support-service
  ports:
  - port: 9060
    targetPort: 9060
  type: ClusterIP 