apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service
        image: umutgu/customer-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9020
        env:
        - name: SPRING_CLOUD_CONFIG_PROFILE
          value: "dev"
        - name: CONFIGURL
          value: "http://config-server:8090"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9020
          initialDelaySeconds: 90
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9020
          initialDelaySeconds: 90
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
  - port: 9020
    targetPort: 9020
  type: ClusterIP 