name: User Service Unit Tests

on:
  push:
    paths:
      - 'user-service/**'
    branches: [ main, master ]
  pull_request:
    paths:
      - 'user-service/**'
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build and Test
      run: |
        cd user-service
        mvn clean test
    
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Maven Tests
        path: user-service/target/surefire-reports/*.xml
        reporter: java-junit 